### ISSUE TITLE
tealium-carthage.json has not been updated for 5.5.2

### ISSUE THREAD

**Issue by KITSSebSkuse** [Tealium/tealium-ios#109]
As per the title - https://raw.githubusercontent.com/Tealium/tealium-ios/master/tealium-carthage.json doesn't have a reference to the 5.5.2 release, so isn't detected as an update by Carthage.

**Comment by craigrouse** [comment]
@KITSSebSkuse Apologies for this. I have just updated the file.

Please note: you must use the location specified in the [docs](https://docs.tealium.com/platforms/ios/install/), since GitHub hosting does not return the correct content-type header for JSON files, which means Carthage fails to recognise it. Thanks for bringing this to our attention.
