### ISSUE TITLE
Duplicated Issue

### ISSUE THREAD

**Issue by ghousesgb** [Tealium/tealium-ios#21]

**Comment by jalakoo** [comment]
@ghousesgb Thanks for the inquiry.  Answers per line item:
1. TealiumDSK_OverrideURL has been replaced with the TEALConfiguration properties 'overridePublishSettingsURL' for getting remote configuration data and 'overrideTagManagementURL' for overriding where to retrieve the Tealium's UTAG.js from (see our API docs at: http://tealium.github.io/tealium-ios/Classes/TEALConfiguration.html#//api/name/overridePublishSettingsURL)
2. addGlobalCustomData has been replaced with 'addPersistentDataSources:'
3. addCustomData:toObject: & removeCustomDataForKeys:forObject: have been deprecated because auto tracking was removed.  Recommend using the optional dataSources argument in 'trackEventWithTitle:dataSources:' method.
4. A view object does not need to be passed into the  'trackViewWithTitle:dataSources' method because auto tracking and object associated data tracking has been removed for increased stability.
5. Log output is auto set to the environment you passed into the init line.  So, 'dev' = verbose logs, 'qa' = warnings and errors, 'prod' = errors only.  Additionally, these can be overwritten from your Tealium mobile publish settings accessible through the Tealium TIQ dashboard at: my.tealiumiq.com

**Comment by ghousesgb** [comment]
Thanks for answers, Gotta few more questions
1. What is the replacement method for +(NSMutableDictionary *)globalCustomData method,
2. When do we use addVolatileDataSource method.
3. How to fetch UUID generated by tealium SDK, I tried it by saying [self.tealiumInstanceId][TEALDataSourceKey_UUID] but no luck.
