### ISSUE TITLE
Increasing numbers of duplicate analytics requests for each single Tealium request

### ISSUE THREAD

**Issue by interstateone** [Tealium/tealium-ios#53]
When observing HTTP(S) requests with Charles in order to verify our analytics events were being tracked as expected, we noticed that there were duplicate requests being sent to Adobe Marketing Cloud. Specifically: for each request to Tealium we would expect one corresponding request to AMC to be made after the response from Tealium completes. What we actually see is that for the nth single request to Tealium, there will be n requests to AMC.

For example:

1. The app will execute code like `tealiumInstance.trackView(withTitle: tag, dataSources: context)`
2. We can observe a single request to `https://collect-us-east-1.tealiumiq.com/**/i.gif` which succeeds
3. We can observe n requests to `https://*.2o7.net`, where n is the index of this request. If this is the 30th view tracking event, then 30 requests are made to AMC. The next one will make 31 requests. All of these succeed. They all have the exact same timestamps.

As you can imagine, if the user navigates through this app for a while, each individual page view will end up sending a large number of requests. Because all of the AMC requests succeed it doesn't seem like this is happening because a failed request is being retried. It's not clear to me what might be causing this, so I'm hoping that you may have some insight.

**Comment by craigrouse** [comment]
@interstateone this is actually an issue with the AMC code loaded through Tealium iQ. It's not an issue related to the iOS library directly.

There is a solution available that the support team will be able to help you implement. Please get in touch with support@tealium.com, and I recommend linking to this issue.

Closing for now, since it's an issue with the vendor tag, rather than the library itself.

Thanks,

Craig.
