### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by MapaX** [Tealium/tealium-ios#58]
This project is not supporting carhage as package manager.
It would be really nice if this library could be added to project through carthage.

**Comment by craigrouse** [comment]
@MapaX I have a quick question on this. Since Carthage now supports binary-only frameworks, this is possible. The simplest thing for us to do would be to host a JSON file that points to the GitHub release zip file for each versioned release. i.e.:

```
{
	"1.0": "https://github.com/Tealium/tealium-ios/archive/5.3.1.zip"
}
```

 I've tested this locally, and this results in all the .framework files at the root of the repo being downloaded when you run `carthage update`. Would that be a problem for you with your workflow? We could also go down the route of separately hosting zip files containing only individual frameworks, but then you'd need multiple separate Cartfile entries if you needed more than 1 framework (e.g. TealiumIOS and TealiumIOSLifecycle). This would add complexity, but you would only get the frameworks you actually need. What would be your preference? Do you have any better suggestions? Full Carthage support is already provided by our Swift library, which you may like to take a look at: https://github.com/tealium/tealium-swift. This library is available with source code, which makes Carthage support much easier.

**Comment by MapaX** [comment]
I think the binary only framework would be sufficient for our purposes.
We are looking to take the swift version in to use in some point, but it will take some time before that happens. In meantime the binary version would be nice solution.

**Comment by JuhaO81** [comment]
Any updated here?

**Comment by craigrouse** [comment]
@JuhaO81 I have put up a branch containing a JSON release. To use it, put the following in your Cartfile:

`binary "https://raw.githubusercontent.com/Tealium/tealium-ios/carthage-support/tealium-carthage.json"`

Optionally, if you require a specific version, you can use a version number:

`binary "https://raw.githubusercontent.com/Tealium/tealium-ios/carthage-support/tealium-carthage.json" ~> 5.4.4`

Please let me know if this works for you. If so, we will push it to master. I've added support for 5.4.4, right back to 5.2.0.

Let me know how you get on.

**Comment by craigrouse** [comment]
@JuhaO81 @MapaX With the latest release, the Carthage json file is hosted here: https://github.com/Tealium/tealium-ios/blob/master/tealium-carthage.json

I'll close this now, but let me know if you have any questions or issues.

**Comment by craigrouse** [comment]
Update: I've found an issue with using the GitHub raw location; it doesn't return the correct content-type headers. Please use this location instead: 

https://tags.tiqcdn.com/dle/tealiummobile/tealium-ios-carthage/tealium-carthage.json

This will be added to the install documentation.

**Comment by craigrouse** [comment]
Documentation now updated: https://community.tealiumiq.com/t5/Tealium-for-iOS/Adding-Tealium-to-Your-iOS-App/ta-p/16327#toc-hId--445660460
