### ISSUE TITLE
Issues in latest library

### ISSUE THREAD

**Issue by roelspruit** [Tealium/tealium-ios#97]
Hi,

The latest version of the SDK is giving me some linker warnings during build. Maybe it was built incorrectly?

`ld: warning: linking ObjC for iOS Simulator, but dylib (/Users/roel/Projects/Funda/Funda.iOS/Funda/Pods/TealiumIOS/TealiumIOS.framework/TealiumIOS) was compiled for MacOSX`

Additionally, we get the following error:

`..../Pods/TealiumIOS/TealiumIOS.framework/Headers/TEALConsentManager.h:26:1: [31mconflicting nullability specifier on return types, '_Nullable' conflicts with existing specifier 'nonnull'`

**Comment by jonathanswong** [comment]
Hi @roelspruit . Thanks for the info. We'll give it a look.

**Comment by jonathanswong** [comment]
Hi @roelspruit . For the warning on TEALConsentManager, that won't affect you using Consent Manager, but it will be fixed in the next release. 

I'm not seeing the same issue for linking with TealiumIOS however. If you `lipo -info TealiumIOS.framework/TealiumIOS.framework`, you should get an output that matches: 
`Architectures in the fat file: TealiumIOS.framework/TealiumIOS are: i386 x86_64 armv7 arm64` which are the required architectures for the simulator and device. If there is a problem running TealiumIOS on either the simulator or device, please let us know. In the meantime, we'll keep an eye on this and see if it is fixed in our next releaes. Thanks.

**Comment by roelspruit** [comment]
Hi @jonwong-tealium 

Unfortunately the ConsentManager issue actually causes a failing build. It is an error, not a warning.

**Comment by jonathanswong** [comment]
HI @roelspruit . Do you have a build setting that is treating warnings as an error? With both Cocoapods and by manually embedding the binary, you do see the message as a warning but not as an error. Thanks.

**Comment by roelspruit** [comment]
Hi @jonwong-tealium 
We have warnings as errors on but this is an actual error for us. I found out that this only happened during our archiving step, which uses a release configuration. For this release configuration we had Whole Module optimisation enabled. Disabling whole module optimisation makes the error disappear on my local machine but our CI system still throws the error. I'll continue to investigate the issue so see if I can pinpoint the exact cause. It would be great if you could prioritise the codechange in the library itself just in case I cannot work around it.

**Comment by jonathanswong** [comment]
Hi @roelspruit . Please check out release 5.4.10. This should fix both errors you listed. If it isn't fixed, I'll reopen the issue. Thank you.

**Comment by roelspruit** [comment]
Thanks for the quick response! it seems to resolve the errors.
